# Generated by Django 2.1 on 2019-06-22 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='career',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apicore.Career'),
        ),
    ]
