# Generated by Django 2.1 on 2019-04-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='port',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
