# Generated by Django 2.1 on 2019-11-16 05:03

import apicore.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apicore', '0002_auto_20190622_0313'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('command', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'comando para ejecutar',
                'verbose_name_plural': 'comandos para ejecutarse',
                'ordering': ['action'],
            },
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Tipo de archivo',
                'verbose_name_plural': 'Tipos de archivos',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='commandserver',
            name='file_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apicore.FileType', verbose_name='Tipo'),
        ),
    ]
