# Generated by Django 2.1 on 2020-01-18 04:30

import apicore.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apicore', '0003_auto_20191116_0503'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apicore.models.custom_upload_to, verbose_name='Avatar')),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfiles',
                'ordering': ['user__username'],
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='career',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='career',
            options={'ordering': ['name'], 'verbose_name': 'carrera'},
        ),
        migrations.AlterModelOptions(
            name='extension',
            options={'ordering': ['name'], 'verbose_name': 'extension', 'verbose_name_plural': 'extensiones'},
        ),
        migrations.AlterModelOptions(
            name='filesuser',
            options={'ordering': ['user__username'], 'verbose_name': 'archivo por usuario', 'verbose_name_plural': 'archivos por usuario'},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['hostname'], 'verbose_name': 'servidor', 'verbose_name_plural': 'servidores'},
        ),
        migrations.AlterModelOptions(
            name='serveruser',
            options={'ordering': ['user__username'], 'verbose_name': 'sesión de usuario', 'verbose_name_plural': 'sesiones de usuario'},
        ),
        migrations.RemoveField(
            model_name='filesuser',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='filesuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='filesuser',
            name='path',
        ),
        migrations.RemoveField(
            model_name='filesuser',
            name='size',
        ),
        migrations.AddField(
            model_name='filesuser',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apicore.models.custom_upload_to_media, verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='career',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='career',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='commandserver',
            name='action',
            field=models.CharField(max_length=50, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='commandserver',
            name='command',
            field=models.CharField(max_length=200, verbose_name='Comando'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='server',
            name='hostname',
            field=models.CharField(max_length=200, verbose_name='Nombre del Servidor'),
        ),
        migrations.AlterField(
            model_name='server',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='Dirección IP'),
        ),
        migrations.AlterField(
            model_name='server',
            name='mac_address',
            field=models.CharField(max_length=150, verbose_name='Dirección MAC'),
        ),
        migrations.AlterField(
            model_name='server',
            name='pin',
            field=models.CharField(max_length=5, verbose_name='PIN de acceso'),
        ),
        migrations.AlterField(
            model_name='server',
            name='port',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Puerto'),
        ),
        migrations.AlterField(
            model_name='server',
            name='screen',
            field=models.BooleanField(default=True, verbose_name='Estado de Pantalla'),
        ),
        migrations.AlterField(
            model_name='server',
            name='volume',
            field=models.IntegerField(default=100, verbose_name='Volumen'),
        ),
        migrations.AlterField(
            model_name='serveruser',
            name='connect_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de conexión'),
        ),
        migrations.AlterField(
            model_name='serveruser',
            name='last_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Útima fecha de activdad'),
        ),
        migrations.AlterField(
            model_name='serveruser',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apicore.Server', verbose_name='Servidor'),
        ),
        migrations.AlterField(
            model_name='serveruser',
            name='session',
            field=models.CharField(max_length=250, verbose_name='Id de sesión'),
        ),
        migrations.AlterField(
            model_name='serveruser',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='serveruser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='career',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apicore.Career', verbose_name='Carrera'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
