# Generated by Django 2.1 on 2019-04-13 04:59

import apicore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0003_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__username']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apicore.models.custom_upload_to),
        ),
    ]
