# Generated by Django 2.1 on 2020-01-18 04:56

import apicore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0004_auto_20200118_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesuser',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apicore.models.custom_upload_to_media, verbose_name='Archivo Multimedia'),
        ),
    ]
