# Generated by Django 2.1 on 2020-02-05 04:22

import apicore.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apicore', '0006_filetype_extensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesuser',
            name='file',
            field=models.FileField(default=None, upload_to=apicore.models.custom_upload_to_media, verbose_name='Archivo Multimedia'),
        ),
        migrations.AlterField(
            model_name='filesuser',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apicore.Server'),
        ),
        migrations.AlterField(
            model_name='filetype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
